// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
    // Solo para `prisma migrate diff --from-migrations` (ver .claude/rules/migrations.md).
    // Debe ser una BD distinta de `url` (Prisma la borra y recrea).
    shadowDatabaseUrl: process.env['SHADOW_DATABASE_URL'],
  },
});
